### ISSUE TITLE
installer: Error the package path specified was invalid

### ISSUE THREAD

**Issue by geeyan** [othercat/CJKFontScript#6]
installer: Error the package path specified was invalid: '/Users/{xx}/Desktop/YosemiteFactorialChineseGUIFontRecovery.pkg'.

**Comment by ShikiSuen** [comment]
1. Yosemite Factorial Chinese GUI Font Recovery package won't be offered on GitHub anymore, and will be available here until September 30:
   https://originhansansui.codeplex.com/releases/view/615922
2. If you are planning to upgrade to OS X El Capitan, you won't need this package since OS X El Capitan Installer would clean up all system font settings first.

**Comment by ShikiSuen** [comment]
One more thing: I checked the release channel of this repo and have found such package is still hosted here. Then I thought you might have encountered network glitches.
